name: Backend CI Checks

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle Checks
        env:
            MAIL_FROM : ${{ secrets.MAIL_FROM}}
            MAIL_HOST : ${{ secrets.MAIL_HOST}}
            MAIL_PASSWORD : ${{ secrets.MAIL_PASSWORD}}
            MAIL_PORT : ${{ secrets.MAIL_PORT}}
            MAIL_USERNAME : ${{ secrets.MAIL_USERNAME}}
            SPARKPOST_API_KEY : ${{ secrets.SPARKPOST_API_KEY}}
        run: ./gradlew check
